web20_1/web20_1/models/topic.py
import time
from models import Model


class Topic(Model):
    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def __init__(self, form):
        self.id = None
        self.views = 0
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.ct = int(time.time())
        self.ut = self.ct
        self.user_id = form.get('user_id', '')
        self.board_id = int(form.get('board_id', -1))

    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m

    def user(self):
        from .user import User
        u = User.find(self.user_id)
        return u

web20_1/web20_1/routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    abort)

from models.user import User

from utils import log

main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


# @main.route("/")
# def index():
#     u = current_user()
#     return render_template("index.html", user=u)

@main.route("/")
def index():
    u = current_user()
    return redirect(url_for('topic.index'))



@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u)


@main.route('/gua')
def gua():
    # xss 攻击的后台
    cookie = request.args.get('cookie')
    log('cookie', cookie)


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.find(id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)

web20_1/web20_1/routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    print('DEBUG', form)
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

web20_1/web20_1/routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)

from routes import *

from models.topic import Topic
from models.board import Board
import uuid
import markdown



main = Blueprint('topic', __name__)


csrf_tokens = dict()


@main.route("/")
def index():
    # board_id = 2
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.find_all(board_id=board_id)
    u = current_user()
    token = str(uuid.uuid4())
    csrf_tokens[token] = u.id
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


# @main.route("/add", methods=["POST"])
# def add():
#     form = request.form
#     u = current_user()
#     m = Topic.new(form, user_id=u.id)
    # m = Topic.new(form)
    # return redirect(url_for('.detail', id=m.id))
#

@main.route("/add", methods=["POST"])
def add():
    form = request.form
    m = Topic.new(form, user_id=u.id)


# @main.route("/delete")
# def delete():
#     id = int(request.args.get('id'))
#     u = current_user()
#     print('删除 topic 用户是', u, id)
#     Topic.delete(id)
#     return redirect(url_for('.index'))
#
@main.route("/delete")
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    # 判断 token 是否是我们给的
    token = request.args.get('token')
    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        print('删除 topic 用户是', u, id)
        Topic.delete(id)
        return redirect(url_for('.index'))
    else:
        abort(403)


def new_csrf_token():
    u = current_user()
    token = str(uuid.uuid4())
    csrf_tokens[token] = u.id
    return token


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    return render_template("topic/new.html", bs=bs, bid=board_id)

web20_1/web20_1/templates/topic/detail.html
{% extends "base.html" %}
{% block main %}

 <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 2 天前
            </span>
                    <span>
                {% set u = topic.user() %}
                作者
                <a href="{{ url_for('index.user_detail', id=u.id) }}">
                    {{ u.username }}
                </a>
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 问答
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-body"></div>
                    {{ topic.content |markdown |safe}}
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
            {% set u = r.user() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <a href="{{ url_for('index.user_detail', id=u.id) }}" class="user_avatar">
                        <img src="https://avatars2.githubusercontent.com/u/10721874?v=3&amp;s=120"
                             title="{{ u.username }}"/>
                    </a>
                    <div class='user_info'>
                        <a class='dark reply_author'>
                            {{ u.username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 / {{ loop.length }}楼 •
                            <span class="gua-time" id="{{ r.ct }}"></span>
                        </a>
                    </div>
                    <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text"></div>
{#                    <div class="markdown-text"></div>#}
                </div>
            </div>
        {% endfor %}
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
</div>
</body>

<script class='gua-markdown' type='text/plain'>
{{ topic.content | safe }}

</script>
{% for r in topic.replies() %}
<script class='gua-markdown' type='text/plain'>
{{ r.content | safe }}
</script>
{% endfor %}


{% endblock %}

web20_1/web20_1/templates/topic/index.html
{% extends "base.html" %}
{% block main %}

    <div id="sidebar">
        <div class="panel">
            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="topic_full_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>

                            <div class="markdown-body"> {{t.content | markdown}}</div>

                            <a class="topic_title" href="{{ url_for('topic.delete', id=t.id) }}">
                            <a class="topic_title" href="{{ url_for('topic.delete', id=t.id) }}">删除</a>

                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

web20_1/web20_1/templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>

    <link href="http://twitter.github.com/bootstrap/assets/js/google-code-prettify/prettify.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">

    <script src="http://cdn.bootcss.com/jquery/1.9.1/jquery.min.js"></script>
    <!--键盘事件-->
    <script src="https://mindmup.s3.amazonaws.com/lib/jquery.hotkeys.js"></script>
    <script src="http://cdn.bootcss.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/css/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/js/webuploader.withoutimage.js"></script>
    <script src="/static/js/bootstrap-wysiwyg.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
    <style>
            #editor {overflow:scroll; max-height:300px ; width: 95%;}
            .btn-toolbar{ width: 100%;}
    </style>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            {% for b in bs %}
                {% if bid == b.id %}
                    <option value="{{ b.id }}" selected="selected" >{{ b.title }}</option>
                {% else %}
                    <option value="{{ b.id }}" >{{ b.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>

            <textarea id='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>

        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    $('#editor').wysiwyg();
  })();
</script>

</body>
</html>

web20_1/web20_1/templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>